const languages = [
    { lang: "Hindi", id: "hi" },
    { lang: "Afrikaans", id: "af" },
    { lang: "Albanian", id: "sq" },
    { lang: "Amharic", id: "am" },
    { lang: "Arabic", id: "ar" },
    { lang: "Armenian", id: "hy" },
    { lang: "Azerbaijani", id: "az" },
    { lang: "Basque", id: "eu" },
    { lang: "Belarusian", id: "be" },
    { lang: "Bengali", id: "bn" },
    { lang: "Bosnian", id: "bs" },
    { lang: "Bulgarian", id: "bg" },
    { lang: "Catalan", id: "ca" },
    { lang: "Cebuano", id: "ceb" },
    { lang: "Chichewa", id: "ny" },
    { lang: "Chinese (Simplified)", id: "zh-CN" },
    { lang: "Chinese (Traditional)", id: "zh-TW" },
    { lang: "Corsican", id: "co" },
    { lang: "Croatian", id: "hr" },
    { lang: "Czech", id: "cs" },
    { lang: "Danish", id: "da" },
    { lang: "Dutch", id: "nl" },
    { lang: "English", id: "en" },
    { lang: "Esperanto", id: "eo" },
    { lang: "Estonian", id: "et" },
    { lang: "Filipino", id: "tl" },
    { lang: "Finnish", id: "fi" },
    { lang: "French", id: "fr" },
    { lang: "Frisian", id: "fy" },
    { lang: "Galician", id: "gl" },
    { lang: "Georgian", id: "ka" },
    { lang: "German", id: "de" },
    { lang: "Greek", id: "el" },
    { lang: "Gujarati", id: "gu" },
    { lang: "Haitian Creole", id: "ht" },
    { lang: "Hausa", id: "ha" },
    { lang: "Hawaiian", id: "haw" },
    { lang: "Hebrew", id: "iw" },
  
    { lang: "Hmong", id: "hmn" },
    { lang: "Hungarian", id: "hu" },
    { lang: "Icelandic", id: "is" },
    { lang: "Igbo", id: "ig" },
    { lang: "Indonesian", id: "id" },
    { lang: "Irish", id: "ga" },
    { lang: "Italian", id: "it" },
    { lang: "Japanese", id: "ja" },
    { lang: "Javanese", id: "jw" },
    { lang: "Kannada", id: "kn" },
    { lang: "Kazakh", id: "kk" },
    { lang: "Khmer", id: "km" },
    { lang: "Kinyarwanda", id: "rw" },
    { lang: "Korean", id: "ko" },
    { lang: "Kurdish (Kurmanji)", id: "ku" },
    { lang: "Kyrgyz", id: "ky" },
    { lang: "Lao", id: "lo" },
    { lang: "Latin", id: "la" },
    { lang: "Latvian", id: "lv" },
    { lang: "Lithuanian", id: "lt" },
    { lang: "Luxembourgish", id: "lb" },
    { lang: "Macedonian", id: "mk" },
    { lang: "Malagasy", id: "mg" },
    { lang: "Malay", id: "ms" },
    { lang: "Malayalam", id: "ml" },
    { lang: "Maltese", id: "mt" },
    { lang: "Maori", id: "mi" },
    { lang: "Marathi", id: "mr" },
    { lang: "Mongolian", id: "mn" },
    { lang: "Myanmar (Burmese)", id: "my" },
    { lang: "Nepali", id: "ne" },
    { lang: "Norwegian", id: "no" },
    { lang: "Odia (Oriya)", id: "or" },
    { lang: "Pashto", id: "ps" },
    { lang: "Persian", id: "fa" },
    { lang: "Polish", id: "pl" },
    { lang: "Portuguese", id: "pt" },
    { lang: "Punjabi", id: "pa" },
    { lang: "Romanian", id: "ro" },
    { lang: "Russian", id: "ru" },
    { lang: "Samoan", id: "sm" },
    { lang: "Scots Gaelic", id: "gd" },
    { lang: "Serbian", id: "sr" },
    { lang: "Sesotho", id: "st" },
    { lang: "Shona", id: "sn" },
    { lang: "Sindhi", id: "sd" },
    { lang: "Sinhala", id: "si" },
    { lang: "Slovak", id: "sk" },
    { lang: "Slovenian", id: "sl" },
    { lang: "Somali", id: "so" },
    { lang: "Spanish", id: "es" },
    { lang: "Sundanese", id: "su" },
    { lang: "Swahili", id: "sw" },
    { lang: "Swedish", id: "sv" },
    { lang: "Tajik", id: "tg" },
    { lang: "Tamil", id: "ta" },
    { lang: "Tatar", id: "tt" },
    { lang: "Telugu", id: "te" },
    { lang: "Thai", id: "th" },
    { lang: "Turkish", id: "tr" },
    { lang: "Turkmen", id: "tk" },
    { lang: "Ukrainian", id: "uk" },
    { lang: "Urdu", id: "ur" },
    { lang: "Uyghur", id: "ug" },
    { lang: "Uzbek", id: "uz" },
    { lang: "Vietnamese", id: "vi" },
    { lang: "Welsh", id: "cy" },
    { lang: "Xhosa", id: "xh" },
    { lang: "Yiddish", id: "yi" },
    { lang: "Yoruba", id: "yo" },
    { lang: "Zulu", id: "zu" },
    { lang: "Hebrew", id: "he" },
    { lang: "Chinese (Simplified)", id: "zh" },
  ];
  export default languages;